---
- hosts: all
  become: yes
  tasks: 
    - name: ping
      ping: 
        data: crash

---
- hosts: all
  tasks: 
    - name: install tree
      apt: 
        name: tree
        state: present


