all:
  hosts:
    192.168.56.105
    192.168.56.102
  children:
    webservers:
      hosts:
        192.168.56.105
        package_name: httpd
        php_module:
          - php
          - php-mysql
        192.168.56.102
        package_name: apache2
        php_module:
          - php
          - libapache2-mod-php
          - php-cli
